### PR TITLE
Implement test script to test more quickly

### PR DESCRIPTION
**Pull request by dslmeinte**
Test script: `test-all.sh`

**Note** that the checks will fail, but that just shows that we were missing problems before :)

### CODE REVIEW

**Comment by joswarmer** [comment]
npm run lint does not work anymore,:
   `jos@fruity core % npm run lint`
  `npm ERR! Lifecycle script `lint` failed with error:   `
 `npm ERR! Error: Missing script: "lint"`

**Comment by joswarmer** [comment]
> 

Second time I run. it, it does work, weird.

**Comment by indamutsa** [comment]
Hi @dslmeinte, I reviewed the README and noticed that it requires sudo permission to run the scripts build-all.sh and test-all.sh, due to EACCES permission denied when run without sudo. However, I also noticed that the test-all.sh script throws an error at the end, despite working well in most cases.
test-all script ERROR

**Comment by indamutsa** [comment]
I will update the README to include the necessary steps before running the scripts, such as switching to the correct directory and using sudo where needed.

**Comment by dslmeinte** [comment]
This PR/branch was already merged. The problem with the non-existing path in the screenshot is known and @joswarmer is fixing it.

**Comment by dslmeinte** [comment]
Also: there should not be necessary steps to run these scripts except for a global "npm i" (as the GH Action does).

**Comment by indamutsa** [comment]
@dslmeinte  Thank you for clarifying. Could you please review the new README (from the branch pr-#79) I just pushed? After merging, you can delete the branch or let me know, and I'll delete it.

**Pull request merged**
